### ISSUE TITLE
Dockerization and automatic image build

### ISSUE THREAD

**Issue by Gnnng** [Zilliqa/nucleus-wallet#16]
The dockerization of this app would help us to deploy this in the Kubernetes cluster and also makes it possible to let the community to try it out easily.

There might be a few things to note for dockerization
1. To stay on the safe side, it's better to create a dedicated user in `Dockerfile` and use `USER` to switch from `root` to the non-root user.
2. About the parameterzation of the API endpoint. We can choose to skip it during the build and pass it onlye when starting the application. Or there's an alternative if the static html can be generated with the API endpoint baked into it. 
3. We can choose where to build the image (Travis, Docker Hub automated build) and what is the eventual form of the image (an application image that is ready to run or a generator image that is used to generate the static html page like we did for [Zilliqa-Wallet](https://github.com/Zilliqa/Zilliqa-Wallet/blob/master/Dockerfile))

**Comment by noelyoo** [comment]
Closed with https://github.com/Zilliqa/nucleus-wallet/pull/19
