### ISSUE TITLE
Faucet should as for address only

### ISSUE THREAD

**Issue by evesnow91** [Zilliqa/nucleus-wallet#45]
Currently, you are required to log in to your wallet via Keystore file or Private key import. This might it difficult for the requester if they are not using dev-wallet to generate their keys. (e.g. Moonlet/ZilPay users)

The workflow should be changed to this:
- Enter `zil1` address
- Do ReCAPTCHA
- Get funds

**Comment by edisonljh** [comment]
Agreed, user should not have to enter private key to get testnet tokens
