### ISSUE TITLE
Add support for ZIL to USD conversion in Tx Calculator

### ISSUE THREAD

**Issue by edisonljh** [Zilliqa/nucleus-wallet#51]
CMC has an API to retrieve ZIL-USD price.

Suggestion: Have a scheduled job that fetches periodically and cache it in order to minimise number of API calls.

**Comment by noelyoo** [comment]
Ok, I will use [Cloud Scheduler](https://cloud.google.com/scheduler) and Cloud Pub/Sub to schedule Function.
